language: cpp

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make && make test

addons:
  apt:
    packages:
      - libasound2-dev

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: g++
    - os: linux
      dist: xenial
      compiler: clang
    - os: osx
      compiler: clang
