language: cpp

before_script:
  - mkdir build
  - mkdir -p build/header_only/ezmidi
  - python scripts/make_header_only.py build/header_only/ezmidi/ezmidi.hpp
  - cd build
  - cmake .. -DTEST_HEADER_ONLY=ON

script:
  - make && make test

addons:
  apt:
    packages:
      - libasound2-dev

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: g++
    - os: linux
      dist: xenial
      compiler: clang
    - os: osx
      compiler: clang
