version: '{build}'

image: Visual Studio 2017
  
clone_folder: 'c:\development\ezmidi'

environment:
  matrix:
    - cmake_generator: '"Visual Studio 15 2017" -A Win32'
    - cmake_generator: '"Visual Studio 15 2017" -A x64'
    
before_build:
  - 'mkdir c:\development\ezmidi\build'
  - 'cd c:\development\ezmidi\build'
  - 'cmake .. -G %cmake_generator%'
    
configuration:
  - Release
  
build:
  project: 'c:\development\ezmidi\build\ezmidi.sln'
  
#test_script: 
#  - 'cd C:\development\ezmidi\build'
#  - 'ctest -C Release'