version: '{build}'

image: Visual Studio 2017
  
clone_folder: 'c:\ezmidi'

environment:
  matrix:
    - cmake_generator: '"Visual Studio 15 2017" -A Win32'
    - cmake_generator: '"Visual Studio 15 2017" -A x64'
    
before_build:
  - 'mkdir -p c:\build\ezmidi\header_only\ezmidi'
  - 'cd c:\build\ezmidi'
  - 'python c:\ezmidi\scripts\make_header_only.py c:\build\ezmidi\header_only\ezmidi\ezmidi.hpp'
  - 'cmake c:\ezmidi -DTEST_HEADER_ONLY=ON -G %cmake_generator%'
    
configuration:
  - Release
  
build:
  project: 'c:\build\ezmidi\ezmidi.sln'
  
test_script: 
  - 'cd C:\build\ezmidi'
  - 'ctest -C Release'