version: '{build}'

image: Visual Studio 2017
  
clone_folder: 'c:\ezmidi'

environment:
  matrix:
    - cmake_generator: '"Visual Studio 15 2017" -A Win32'
    - cmake_generator: '"Visual Studio 15 2017" -A x64'
    
before_build:
  - 'mkdir -p c:\build\ezmidi'
  - 'cd c:\build\ezmidi'
  - 'cmake c:\ezmidi -G %cmake_generator%'
    
configuration:
  - Release
  
build:
  project: 'c:\build\ezmidi\ezmidi.sln'
  
test_script: 
  - 'cd C:\build\ezmidi'
  - 'ctest -C Release'